volumes:
    portainer_data:
      external: true
      name: datos_portainer

services:
  portainer:
    image: portainer/portainer-ce:2.20.1
    container_name: mireg
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - 9000:9000
    restart: always